# Generated by Django 4.2.29 on 2026-03-12 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField(default=1000)),
                ('height', models.IntegerField(default=700)),
                ('background_color', models.CharField(default='#F8F9FA', max_length=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='floor_plan', to='api.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=10)),
                ('shape', models.CharField(choices=[('round', 'Round'), ('square', 'Square'), ('rectangular', 'Rectangular')], default='round', max_length=20)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('width', models.FloatField(default=80)),
                ('height', models.FloatField(default=80)),
                ('rotation', models.FloatField(default=0)),
                ('capacity', models.IntegerField(default=4)),
                ('min_capacity', models.IntegerField(default=1)),
                ('floor_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='api.floorplan')),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_index', models.IntegerField()),
                ('label', models.CharField(max_length=10)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='api.table')),
            ],
            options={
                'ordering': ['seat_index'],
                'unique_together': {('table', 'seat_index')},
            },
        ),
        migrations.CreateModel(
            name='SeatReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_reservations', to='api.reservation')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='api.seat')),
            ],
            options={
                'unique_together': {('reservation', 'seat')},
            },
        ),
    ]
