# Generated by Django 4.2.30 on 2026-05-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='occasion',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
