# Generated by Django 4.2.30 on 2026-05-21 09:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_reservation_note_occasion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='distance',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='distance_km',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='occasion',
            field=models.CharField(blank=True, choices=[('birthday', 'Cumpleanos'), ('anniversary', 'Aniversario'), ('business', 'Negocios'), ('other', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['date'], name='api_reserva_date_232414_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status'], name='api_reserva_status_b87e2f_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['user', 'date'], name='api_reserva_user_id_1e8597_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['cuisine'], name='api_restaur_cuisine_e54dae_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['location'], name='api_restaur_locatio_2fa3a7_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['restaurant', '-created_at'], name='api_review_restaur_e8a1a3_idx'),
        ),
    ]
