# Generated by Django 4.2.30 on 2026-05-26 12:00

import api.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='note',
            field=api.encrypted_fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='staffcode',
            name='email',
            field=api.encrypted_fields.EncryptedCharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=api.encrypted_fields.EncryptedCharField(blank=True, max_length=500),
        ),
    ]
