# Generated by Django 4.2.30 on 2026-05-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_encrypt_existing_pii_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('no_show', 'No show')], default='confirmed', max_length=20),
        ),
    ]
