# Generated by Django 4.2.30 on 2026-06-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_adminauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
